packages:
  - playgrounds/*
  - packages/*
  - docs

catalog:
  '@vitejs/plugin-vue': ^5.1.4
  '@techassi/eslint-config': ^0.1.1
  '@types/node': ^22.7.5
  vue: ^3.3.7
  typescript: ^5.6.2
  vitepress: ^1.4.0
  eslint: ^8.57.1
  vite: ^5.4.8
  vue-tsc: ^2.1.6
