---
name: Publish Package

on:
  push:
    tags:
      - v*

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Install PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Install NodeJS
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Workspace Packages
        if: ${{ success() }}
        run: pnpm run build

      - name: Publish Workspace Packages
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: pnpm run publish

      - name: Create release
        uses: softprops/action-gh-release@v2.0.8
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
