name: publish-docs

# Once the `preview` input is available, this can also run on PR when docs are
# changed.

on:
  # TODO: Remove before merge, only for testing during PR
  pull_request:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/publish-docs.yaml'
      - '.vitepress/**'
      - 'docs/**'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Install PNPM
        uses: pnpm/action-setup@v4.0.0
        with:
          version: latest

      - name: Install NodeJS
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Docs
        run: pnpm docs:build

      - name: Upload Documentation Artifacts
        if: ${{ success() }}
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: .vitepress/dist

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4.0.5
