---
name: pr-checks

on:
  pull_request

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1

      - name: Check Links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >-
            --exclude-path packages/**/dist
            --exclude https://www.youtube-nocookie.com/
            packages/**/*.ts
            packages/**/*.md
            docs/**/*.md

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12

      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: >-
            --from-ref '${{ github.event.pull_request.base.sha }}'
            --to-ref '${{ github.event.pull_request.head.sha }}'
