name: Pull Request Checks

on:
  pull_request

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.8.0
        with:
          args: >-
            --exclude-path packages/**/dist
            --exclude https://www.youtube-nocookie.com/
            packages/**/*.ts
            packages/**/*.md
            docs/**/*.md
